[build]
builder = "nixpacks"
buildCommand = """
  chmod -R 755 bin/
  ls -la bin/
  ./bin/yt-dlp_linux --version || echo "Failed to run version check"
"""

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
cmds = [
    "chmod 755 bin/yt-dlp_linux"
]